AclObjectIdentities:
    type: entity
    table: acl_object_identities
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        classId:
            type: integer
            unsigned: true
            nullable: false
            column: class_id
        objectIdentifier:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: object_identifier
        entriesInheriting:
            type: boolean
            nullable: false
            column: entries_inheriting
    manyToMany:
        ancestor:
            targetEntity: AclObjectIdentities
            cascade: {  }
            mappedBy: null
            inversedBy: objectentity
            joinTable:
                name: acl_object_identity_ancestors
                joinColumns:
                    -
                        name: object_identity_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ancestor_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        parentObjectentity:
            targetEntity: AclObjectIdentities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_object_identity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
