home:
    pattern:  /
    defaults: { _controller: calaveracustomerBundle:Home:index }

_newsletter:
    pattern:  /newsletter
    defaults: { _controller: calaveracustomerBundle:Newsletter:index }

_calaveracustomer_homepage:
    pattern:  /newsletter/test
    defaults: { _controller: calaveracustomerBundle:Newsletter:test }
    
_newsletterSing:
  pattern: /newsletter/sign
  defaults: { _controller: calaveracustomerBundle:Newsletter:sign }
  
_contacto:
  pattern: /contacto
  defaults: { _controller: calaveracustomerBundle:Contacto:index }
  
_contactoRegistro:
  pattern: /contacto/send
  defaults: { _controller: calaveracustomerBundle:Contacto:sendRegister }

_contactoEmails:
  pattern: /contacto/getEmails
  defaults: { _controller: calaveracustomerBundle:Contacto:getEmails }
  
_soluciones:
  pattern: /soluciones
  defaults: { _controller: calaveracustomerBundle:Soluciones:index }
  
_blog : 
  pattern: /blog
  defaults : { _controller: calaveracustomerBundle:Blog:index }
  
_nosotros :
  pattern: /nosotros
  defaults: { _controller: calaveracustomerBundle:Nosotros:index }

_nosotros_integrntes:
  pattern: /nosotros/integrantes
  defaults: { _controller: calaveracustomerBundle:Nosotros:integrantes }

_nosotros_instalaciones:
  pattern: /nosotros/instalaciones
  defaults: { _controller: calaveracustomerBundle:Nosotros:instalaciones }
  
_servicios:
  pattern: /servicios
  defaults: { _controller: calaveracustomerBundle:Servicios:index }
  
_serviciosWeb:
  pattern: /servicios/web_desing
  defaults: { _controller: calaveracustomerBundle:Servicios:webDesing }
  
_serviciosDisenio:
  pattern: /servicios/graphic_desing
  defaults: { _controller: calaveracustomerBundle:Servicios:graphicDesing }

_serviciosFotografia:
  pattern: /servicios/photography
  defaults: { _controller: calaveracustomerBundle:Servicios:webDesing }
  
_serviciosFotografia:
  pattern: /servicios/photography
  defaults: { _controller: calaveracustomerBundle:Servicios:index }

_portafolio:
  pattern: /portafolio
  defaults: { _controller: calaveracustomerBundle:Portafolio:index }